# Generated by Django 2.2.5 on 2020-07-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='roll',
            field=models.CharField(max_length=10),
        ),
    ]
